#pragma once

#include "CommonTypes.h"

enum class Base32Alphabet {
    RFC4648,
    HEX
};

template<Base32Alphabet Alphabet = Base32Alphabet::RFC4648>
class Base32 {
public:
    template<typename TString = std::string>
    static TString Encode(const ByteSpan& data) {
        // Generated by Copilot

        static_assert(Alphabet == Base32Alphabet::RFC4648 || Alphabet == Base32Alphabet::HEX, "Unsupported base32 alphabet");

        const char* alphabet = (Alphabet == Base32Alphabet::RFC4648) ? "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567" : "0123456789ABCDEFGHIJKLMNOPQRSTUV";

        size_t encodedLen = ((data.size() + 4) / 5) * 8;
        TString encoded(encodedLen, '=');

        size_t dataIndex = 0;
        size_t encodedIndex = 0;

        while (dataIndex < data.size()) {
            uint64_t buffer = 0;
            size_t bytesToProcess = std::min(static_cast<size_t>(5), data.size() - dataIndex);

            for (size_t i = 0; i < bytesToProcess; ++i) {
                buffer <<= 8;
                buffer |= data[dataIndex + i];
            }

            buffer <<= (5 - bytesToProcess) * 8;

            for (size_t i = 0; i < 8; ++i) {
                if (i < ((bytesToProcess * 8 + 4) / 5)) {
                    encoded[encodedIndex++] = alphabet[(buffer >> (35 - i * 5)) & 0x1F];
                }
                else {
                    encoded[encodedIndex++] = '=';
                }
            }

            dataIndex += bytesToProcess;
        }

        return encoded;
    }
};

using Base32Hex = Base32<Base32Alphabet::HEX>;