include "lwdn.fbs";
include "datetime.fbs";

namespace lwt;

table CheckInRequest {
    /// Private token issued by the ticketing system to
    /// start check-in, signed by MOS. This is issued on-demand when a client app
    /// connects to the ticketing system and requests a refresh.
    /// For safety, it should be refreshed as often as possible, but this
    /// is up to the client to decide (failure to refresh could only harm
    /// the customer, by way of paying for someone else's rides).
    account_checkin_token: [ubyte] (required);
}

table CheckInIntermediate {
    /// Confirmation token issued by the LWT device upon validating with MOS that
    /// check-in is possible. It is valid for the local device for a generous time period
    /// (several 10s of minutes). This 2-phase check-in is done so that the client
    /// is informed about their ability to check-in before they issue the final confirmation,
    /// which can be done without MOS's knowledge.
    confirmation_token: [ubyte] (required);
}

table CheckInConfirmation {
    /// Token given by the device in CheckInIntermediate, that the client
    /// can send once it is ready to commit the check-in.
    confirmation_token: [ubyte] (required);
}

table CICOTicketFragment {
    /// List of all LWDN addresses of the fragment issuer.
    issuer_addresses: [LwdnAddress] (required);
    /// DER data of the certificate of the fragment issuer.
    /// This is sent to follow-up peers in CICORefresh requests
    /// so that they can verify that the preceding fragment was
    /// signed by a legitimate issuer.
    issuer_certificate: [ubyte] (required);
    /// The ephemereal electronic ticket data to be shown during inspection.
    /// The signature in this ETD is not using the MOS signing key, but rather
    /// using the LWT device's local key. Since the certificate is quite large
    /// (about 0.5 kB), it is not embedded in the ETD, rather, the ticket inspector
    /// must request it from the vehicle.
    etd: [ubyte] (required);
    /// TOTP seed for dynamic QR codes. The derivation secret is not the same as
    /// with standard tickets - the keys used here are local to the
    /// device and can only be obtained by the ticket inspector via
    /// local communication.
    totp_seed: [ubyte] (required);
    /// Signed refresh token used to create continuation fragments.
    /// This token is opaque, but contains much of the information also present
    /// in this flatbuffer, digitally signed.
    refresh_token: [ubyte] (required);
    /// Time when the fragment was issued, in milliseconds of server time.
    issued_at: long;
    /// Time when the fragment was issued, as an absolute timestamp.
    /// This may not be present if the device does not have access to an
    /// NTP server. In those cases, the fragment can not be continued
    /// with on another vehicle in state of ticket inspection.
    issued_at_absolute: LwtOffsetDateTime;
    /// Validity period of the refresh token, in milliseconds.
    /// The refresh token is still valid for tariffication purposes even after the TTL
    /// expires (such as during long transfers), but it can no longer bypass ticket inspection
    /// during check-in.
    ttl: long;
}

table CICOFragmentRefreshRequest {
    /// Raw data of the fragment's refresh token.
    refresh_token: [ubyte] (required);
    /// DER issuer certificate, for use during transfers (changes of vehicles).
    /// As a special case, if the fragment is being sent to the same peer that it
    /// had originated from, this can be set to a constant 0x5C (single element array)
    /// to prevent needless retransmissions.
    issuer_certificate: [ubyte] (required);
}

table CICORefreshRequest {
    /// The fragment that should be refreshed.
    fragment: CICOFragmentRefreshRequest (required);
}

table CheckOutRequest {
    /// Refresh token of the fragment used to terminate the CICO session.
    /// Only one needs to be sent, as parallel fragments are all still part of one session.
    /// Usage of a refresh token after check-out is not prohibited in a technical manner.
    /// It can still be used and will be billed. The check out is more of a way for the passenger
    /// to indicate "I am off the network, please finalize my fare", which triggers the ticketing
    /// system to evaluate their fare and allow viewing it as a finished journey. Ticket fragments
    /// are still valid up until their TTL expires, and no pending billing will be reversed.
    fragment: CICOFragmentRefreshRequest (required);
}

table CheckOutResponse {
    /// ID of the finished CICO session, which the client may use to look up their fare
    /// in MOS. This is provided for the convenience of not having to extract it out
    /// of the ETD.
    session_id: [ubyte] (required);
}

table CICOSeedDerivationSecret {
    /// The secret contents.
    data: [ubyte] (required);
    /// Start of validity, in ms. of server time.
    valid_from: long;
    /// End of validity, in ms. of server time.
    valid_to: long;
}

table CICOInspectionData {
    /// DER-format certificate for the private key used by the device to sign
    /// ticket fragments and refresh tokens. This can potentially be its own
    /// cert., albeit at the moment it is the same as the TLS certificate.
    device_certificate: [ubyte] (required);
    /// Seed derivation secrets for ticket TOTPs. There may be multiple,
    /// (for a few minutes before all old ticket fragments have expired),
    /// in which case the issued-at attribute from the ETD selects which
    /// one should be used, similarly to normal ticket, where the "valid from"
    /// attribute fulfills this purpose.
    /// Currently, only one secret is returned which is valid throughout the
    /// whole trip of a vehicle, and is changed when the trip or line changes.
    seed_derivation_secrets: [CICOSeedDerivationSecret] (required);
    /// Server timestamp for use with RTT measuring to translate local times to absolute.
    server_time: long;
}