namespace lwt;

enum LineType : ubyte {
    Metro,
    Tram,
    NTram,
    CityBus,
    NCityBus,
    RegBus,
    NRegBus,
    SchoolBus,
    AirportBus,
    DemandBus,
    GenericBus,
    Trolleybus,
    ReplacementBus,
    Funicular,
    Ferry,
    GenericTrain,
    OsTrain,
    RTrain,
    SpTrain,
    ExTrain
}

table StopReference {
    /// Sequence number of the stop within the route. This matches StopInformationStructure.StopIndex in VDV 301,
    /// minus one to account for 1-based -> 0-based indexing.
    sequence_id: ushort;
    /// Unique and stable stop identifier as transmitted by VDV 301 services.
    /// In V2.3CZ1.0, this is the numeric ID from the Ministry of Transport's CIS JŘ station register,
    /// which, as we all know, is an open and freely accessible state information system,
    /// operated in the public interest by our friendly and very non-corrupt authorities ;)
    global_ref_id: uint;
    /// Name of the stop as seen in vehicle information systems. This should match what is seen on
    /// interior LCD screens for maximum passenger convenience.
    name: string (required);
}

table LineInfo {
    /// Line license number, such as 100394. For trains, this can be the train number, similarly as in the name.
    global_ref_id: uint;
    /// Line type, which can be used f.e. for styling.
    type: LineType;
    /// User-friendly line number. Is a string to support substitute transport (X26) and trains (Os 8854).
    /// It may contain more arbitrarily separated numbers if a line number change is going to take place.
    /// It can also be styled using basic inline HTML.
    name: string (required);
    /// Headsign aka the stop name shown in big caps on interior displays. The stop name inside may be adjusted
    /// and enriched with icons/pictograms.
    headsign: StopReference (required);
}

table TripInfo {
    /// Trip license number, as in a printed timetable (CIS JŘ).
    global_ref_id: uint;
    /// Line info.
    line: LineInfo (required);
}

enum LocationState : ubyte {
    AtStop,
    BeforeStop,
    AfterStop
}

table TripStateInfo {
    /// Trip info.
    trip: TripInfo (required);
    /// Delay of the trip in minutes.
    delay: int;
    /// Stop at which the vehicle is currently stationed, is about to depart from or has recently departed from.
    current_departure_stop: StopReference (required);
    /// General position of the trip in relation to current_departure_stop. Most of the time, this will be either
    /// AtStop or BeforeStop. The exception is when the trip has ended its journey, when AfterStop is used to
    /// signal the terminus.
    location_state: LocationState;
}

table TripStopInfo {
    /// ID and name of the stop.
    stop_ref: StopReference (required);
    /// Time of arrival at the stop (scheduled, absolute). Can be -1 if not present.
    /// The value is an Unix timestamp in the time zone of the stop (number of seconds since 1. 1. 1970).
    arr_time: long = -1;
    /// Time of departure from the stop (scheduled, absolute). Can be -1 if not present.
    /// The value is an Unix timestamp in the time zone of the stop (number of seconds since 1. 1. 1970).
    dep_time: long = -1;
    /// List of tariff zones at the stop. These only contain the zones valid for the current
    /// line and the transport authority operating the LWT module. String is comma separated for
    /// memory efficiency (avoid 32bit flatbuffer pointers). If there are multiple transport networks
    /// at the stop, data for each individual one is separated by semicolons and prefixed
    /// with the transport network ID. For example: "PID 8,9;IDOL 4269". If there is only a single
    /// transport network, then there is no information about which one it actually is. This is a limitation
    /// of the vehicle information system which broadcasts the source data.
    tariff_zones: string;
    /// Number of kilometers travelled here from the first stop. Can be NaN if not present in
    /// the data sent by the vehicle information system.
    tariff_kilometers: float;
}

table TripRouteInfo {
    /// Trip info and state.
    trip: TripStateInfo (required);    
    /// All stops of the trip, including already passed.
    stops: [TripStopInfo] (required);
}