# This script was generated by GitHub Copilot

set(LWT_SCHEMAS_ROOT "${CMAKE_CURRENT_LIST_DIR}")
set(LWT_SCHEMAS_REPO_ROOT "${LWT_SCHEMAS_ROOT}/../../../lwt-comm-schemas")
set(LWT_SCHEMAS_FLATC "${LWT_SCHEMAS_REPO_ROOT}/compiler/flatc.exe")
set(LWT_SCHEMAS_SCHEMA_DIR "${LWT_SCHEMAS_REPO_ROOT}")
set(LWT_SCHEMAS_GENERATED_DIR "${LWT_SCHEMAS_ROOT}/generated")
set(LWT_SCHEMAS_GENERATED_INCLUDE_DIR "${LWT_SCHEMAS_GENERATED_DIR}/include")

file(MAKE_DIRECTORY "${LWT_SCHEMAS_GENERATED_INCLUDE_DIR}")

if(NOT EXISTS "${LWT_SCHEMAS_FLATC}")
    message(FATAL_ERROR "flatc generator not found: ${LWT_SCHEMAS_FLATC}")
endif()

file(GLOB LWT_SCHEMAS_FBS_DEPENDENCIES
    "${LWT_SCHEMAS_SCHEMA_DIR}/*.fbs"
)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${LWT_SCHEMAS_FBS_DEPENDENCIES})

set(LWT_SCHEMAS_GENERATED_INCLUDE_DIRS
    "${LWT_SCHEMAS_GENERATED_INCLUDE_DIR}"
)

function(lwt_schemas_generate_flatbuffer schema_name)
    set(schema_path "${LWT_SCHEMAS_SCHEMA_DIR}/${schema_name}")
    get_filename_component(schema_stem "${schema_name}" NAME_WE)
    set(generated_header "${LWT_SCHEMAS_GENERATED_INCLUDE_DIR}/${schema_stem}_generated.h")

    set(needs_generation FALSE)
    foreach(candidate_path IN LISTS LWT_SCHEMAS_FBS_DEPENDENCIES)
        if(NOT EXISTS "${generated_header}" OR "${candidate_path}" IS_NEWER_THAN "${generated_header}")
            set(needs_generation TRUE)
        endif()
    endforeach()

    if(needs_generation)
        execute_process(
            COMMAND "${LWT_SCHEMAS_FLATC}" --cpp -o "${LWT_SCHEMAS_GENERATED_INCLUDE_DIR}" "${schema_name}"
            WORKING_DIRECTORY "${LWT_SCHEMAS_SCHEMA_DIR}"
            RESULT_VARIABLE generator_result
            OUTPUT_VARIABLE generator_stdout
            ERROR_VARIABLE generator_stderr
        )

        if(NOT generator_result EQUAL 0)
            message(FATAL_ERROR
                "flatc generation failed for ${schema_name}\n"
                "stdout:\n${generator_stdout}\n"
                "stderr:\n${generator_stderr}"
            )
        endif()
    endif()

    if(NOT EXISTS "${generated_header}")
        message(FATAL_ERROR "Expected FlatBuffers header was not generated: ${generated_header}")
    endif()
endfunction()

lwt_schemas_generate_flatbuffer("operations.fbs")
lwt_schemas_generate_flatbuffer("packet.fbs")
lwt_schemas_generate_flatbuffer("ticket_validation.fbs")
lwt_schemas_generate_flatbuffer("trip_information.fbs")