package cz.spojenka.lwt.demoapp;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.Service;
import android.bluetooth.BluetoothManager;
import android.content.Context;
import android.content.Intent;
import android.content.pm.ServiceInfo;
import android.os.BatteryManager;
import android.os.Build;
import android.os.Handler;
import android.os.IBinder;
import android.os.Looper;
import android.util.Log;

import java.time.Duration;
import java.util.List;

import androidx.annotation.Nullable;
import androidx.core.app.NotificationCompat;
import cz.spojenka.lwdn.BluetoothLwdnScanner;
import cz.spojenka.lwdn.LwdnScan;
import cz.spojenka.lwdn.LwdnScanConfig;
import cz.spojenka.lwdn.LwdnScanException;
import cz.spojenka.lwdn.LwdnScanResult;
import cz.spojenka.lwt.LwtDeviceType;
import cz.spojenka.lwt.LwtServiceConstants;

public class BleScanService extends Service {

    // Generated by Gemini, to test battery consumption during BLE scan.

    private static final String TAG = "BleScanService";
    private static final String CHANNEL_ID = "ble_scan_service_channel";
    private static final int NOTIFICATION_ID = 1;

    private static boolean isRunning = false;

    private LwdnScan activeScan;
    private BatteryManager batteryManager;
    private Handler handler;

    private long startChargeCounter;
    private long startEnergyCounter;
    private int startCapacity;
    private long startTimeMillis;

    private final Runnable batteryLogger = new Runnable() {
        @Override
        public void run() {
            logBatteryStats();
            handler.postDelayed(this, Duration.ofMinutes(1).toMillis());
        }
    };

    @Override
    public void onCreate() {
        super.onCreate();
        batteryManager = (BatteryManager) getSystemService(Context.BATTERY_SERVICE);
        handler = new Handler(Looper.getMainLooper());
        createNotificationChannel();
    }

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        isRunning = true;
        startForegroundService();
        startScan();
        recordInitialBatteryStats();
        handler.post(batteryLogger);
        return START_STICKY;
    }

    private void startForegroundService() {
        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
                .setContentTitle("BLE Background Scan")
                .setContentText("Scanning for LWT devices...")
                .setSmallIcon(android.R.drawable.stat_sys_data_bluetooth)
                .build();

        startForeground(NOTIFICATION_ID, notification, ServiceInfo.FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE);
    }

    private void startScan() {
        BluetoothManager btm = getSystemService(BluetoothManager.class);
        if (btm == null || btm.getAdapter() == null) {
            Log.e(TAG, "Bluetooth not available");
            stopSelf();
            return;
        }

        BluetoothLwdnScanner scanner = new BluetoothLwdnScanner(this, btm.getAdapter(), LwtServiceConstants.BLE_API_PSM);
        LwdnScanConfig config = new LwdnScanConfig.Builder()
                .setTimeout(null) // Continuous
                .setScanMode(LwdnScanConfig.ScanMode.LOW_POWER)
                .build();

        // Filter to vehicle service type as an example
        var serviceId = LwtServiceConstants.serviceUUIDForDeviceType(LwtDeviceType.VEHICLE);

        activeScan = scanner.startScan(List.of(serviceId), config);
        activeScan.addOnResultListener(new LwdnScan.OnResultListener() {
            @Override
            public void onResult(LwdnScan scan, LwdnScanResult result) {
                Log.d(TAG, "Found device in background: " + result.deviceAddress());
            }

            @Override
            public void onFailure(LwdnScan scan, LwdnScanException e) {
                Log.e(TAG, "Background scan failed", e);
            }
        });
    }

    private void recordInitialBatteryStats() {
        startTimeMillis = System.currentTimeMillis();
        startCapacity = batteryManager.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY);
        startChargeCounter = batteryManager.getLongProperty(BatteryManager.BATTERY_PROPERTY_CHARGE_COUNTER);
        startEnergyCounter = batteryManager.getLongProperty(BatteryManager.BATTERY_PROPERTY_ENERGY_COUNTER);
        Log.i(TAG, "Initial Battery Stats: Capacity=" + startCapacity + "%, Charge=" + startChargeCounter + " uAh, Energy=" + startEnergyCounter + " nWh");
    }

    private void logBatteryStats() {
        int currentCapacity = batteryManager.getIntProperty(BatteryManager.BATTERY_PROPERTY_CAPACITY);
        long currentCharge = batteryManager.getLongProperty(BatteryManager.BATTERY_PROPERTY_CHARGE_COUNTER);
        long currentEnergy = batteryManager.getLongProperty(BatteryManager.BATTERY_PROPERTY_ENERGY_COUNTER);

        long durationMinutes = (System.currentTimeMillis() - startTimeMillis) / (60 * 1000);
        int capacityDiff = startCapacity - currentCapacity;
        long chargeDiff = startChargeCounter - currentCharge;
        long energyDiff = startEnergyCounter - currentEnergy;

        Log.i(TAG, "Battery Consumption (after " + durationMinutes + " min): " +
                "Capacity Drop=" + capacityDiff + "%, " +
                "Charge Consumed=" + chargeDiff + " uAh, " +
                "Energy Consumed=" + energyDiff + " nWh");
    }

    private void createNotificationChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel serviceChannel = new NotificationChannel(
                    CHANNEL_ID,
                    "BLE Scan Service Channel",
                    NotificationManager.IMPORTANCE_LOW
            );
            NotificationManager manager = getSystemService(NotificationManager.class);
            if (manager != null) {
                manager.createNotificationChannel(serviceChannel);
            }
        }
    }

    public static boolean isRunning() {
        return isRunning;
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        isRunning = false;
        if (activeScan != null) {
            activeScan.cancel();
        }
        handler.removeCallbacks(batteryLogger);
        Log.i(TAG, "Service destroyed. Final battery stats logged below.");
        logBatteryStats();
    }

    @Nullable
    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}
