// automatically generated by the FlatBuffers compiler, do not modify

package cz.spojenka.lwt.cicomock.api.lwtclient;

@SuppressWarnings("unused")
public final class LineType {
  private LineType() { }
  public static final int Metro = 0;
  public static final int Tram = 1;
  public static final int NTram = 2;
  public static final int CityBus = 3;
  public static final int NCityBus = 4;
  public static final int RegBus = 5;
  public static final int NRegBus = 6;
  public static final int SchoolBus = 7;
  public static final int AirportBus = 8;
  public static final int DemandBus = 9;
  public static final int GenericBus = 10;
  public static final int Trolleybus = 11;
  public static final int ReplacementBus = 12;
  public static final int Funicular = 13;
  public static final int Ferry = 14;
  public static final int GenericTrain = 15;
  public static final int OsTrain = 16;
  public static final int RTrain = 17;
  public static final int SpTrain = 18;
  public static final int ExTrain = 19;

  public static final String[] names = { "Metro", "Tram", "NTram", "CityBus", "NCityBus", "RegBus", "NRegBus", "SchoolBus", "AirportBus", "DemandBus", "GenericBus", "Trolleybus", "ReplacementBus", "Funicular", "Ferry", "GenericTrain", "OsTrain", "RTrain", "SpTrain", "ExTrain", };

  public static String name(int e) { return names[e]; }
}

